### ISSUE TITLE
Tag dropdown list style is not correct

### ISSUE THREAD

**Issue by craftzdog** [peterbartha/inkdrop-octopus-ui-theme#1]
Hi,

Thanks for creating the great theme!
BTW, I found a bug in it.
The style of the tag dropdown list looks not correct like this:

<img width="498" alt="Screen Shot 2021-08-22 at 18 04 52" src="https://user-images.githubusercontent.com/1332805/130378259-87fe7d0c-874b-4f28-8324-53fd927fb3f4.png">

Can you please fix it?

**Comment by peterbartha** [comment]
Hey,

Thanks for the feedback. I've already fixed it!

Take care!

**Comment by craftzdog** [comment]
It worked! Thanks so much🙏✨
